/*
 * This code is autogenerated by Touch Instinct tools
 */
package container.touchin.ru.testjsonlibraries;

import com.bluelinelabs.logansquare.annotation.JsonEnum;
import com.bluelinelabs.logansquare.annotation.JsonStringValue;

/**
 * Тип АЗС
 */
@JsonEnum
public enum StationType {

    /**
     * Избранная
     */
    @JsonStringValue("0")
    FAVORITE,

    /**
     * Франшизная
     */
    @JsonStringValue("1")
    FRANCHISE,

    /**
     * Фирменная
     */
    @JsonStringValue("2")
    BRANDED,

    /**
     * Автоматическая
     */
    @JsonStringValue("3")
    AUTOMATIC;

}
