/*
 * This code is autogenerated by Touch Instinct tools
 */
package container.touchin.ru.testjsonlibraries;

import com.bluelinelabs.logansquare.annotation.JsonEnum;
import com.bluelinelabs.logansquare.annotation.JsonNumberValue;

/**
 * Статус АЗС
 */
@JsonEnum
public enum StationStatus {

    /**
     * Открыта
     */
    @JsonNumberValue(1)
    OPEN,

    /**
     * Закрыта
     */
    @JsonNumberValue(2)
    CLOSED,

    /**
     * Строится
     */
    @JsonNumberValue(3)
    BUILDING,

    /**
     * Реконструкция
     */
    @JsonNumberValue(4)
    RENOVATION;

}
